[package]
name = "ocp-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
kube = { version = "3.1", features = ["runtime", "derive", "client"] }
k8s-openapi = { version = "0.27", features = ["v1_32"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rcgen = "0.14"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio", "server-auto", "client-legacy", "http1"] }
hyper-rustls = { version = "0.27", default-features = false, features = ["http1", "ring", "tls12"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
http-body-util = "0.1"
bytes = "1"
clap = { version = "4", features = ["derive"] }
tokio-rustls = "0.26"
rustls-pemfile = "2"
rand = "0.8"
url = "2"
base64 = "0.22"
serde_yaml = "0.9"
jsonwebtoken = "9"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.17"
